baseURL = "https://taller-ciudad-espacio2021.github.io/"
languageCode = "en-us"
title = "Taller Espacio y Ciudad 2021"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

summaryLength = 30

[[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Documentación"
    url = "/docs/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Ir al sitio del curso'
  homepage_intro = 'Sitio web de documentación del Taller de Espacio y Ciudad - Magíster Innovación y Diseño UAI 2021.'
  homepage_image = '/images/taller-ciudad-espacio.jpg'

[params.homepage_meta_tags]
  meta_description = "Sitio web personal de documentación del Taller de Espacio y Ciudad."
  meta_og_title = "Taller de Espacio y Ciudad"
  meta_og_type = "website"
  meta_og_url = "https://taller-ciudad-espacio2021.github.io/"
  meta_og_image = "https://taller-ciudad-espacio2021.github.io/images/taller-ciudad-espacio.jpg"
  meta_og_description = "Sitio web personal de documentación del Taller de Espacio y Ciudad."
  meta_twitter_card = "summary"
  meta_twitter_site = "@designlabuai"
  meta_twitter_creator = "@lab_uai"

[params.logo]
  mobile = "/images/logo.png"
  standard  = "/images/logo.png"
